---

- name: Install apt https support
  apt: name=apt-transport-https update_cache=yes

- name: Add Filebeat repository key
  apt_key: url={{ filebeat.repository.debian.gpgkey }} state=present

- name: Add Filebeat repository
  apt_repository: repo={{ filebeat.repository.debian.baseurl }} state=present
